version: '3.8' 
 
services: 
 
  db:
    # container_name: db
    image: postgres:15.0-alpine
    restart: always
    volumes: 
      - postgres_data:/var/lib/postgresql/data/ 
    ports: 
      - 5432:5432 
    env_file: 
      - ./.env 
     
  backend:
    # container_name: back
    build: 
      context: ../backend
      dockerfile: Dockerfile 
    restart: always 
    volumes: 
      - static_dir:/app/static/
      - media_dir:/app/media/
    depends_on: 
      - db 
    env_file: 
      - ./.env
 
  # frontend: 
  #   build: 
  #     context: ../frontend 
  #     dockerfile: Dockerfile 
  #   volumes: 
  #     - ../frontend/:/app/result_build/ 


  frontend:
    # container_name: front
    image: oskalov/frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend
 
  nginx:
    container_name: proxy
    image: nginx:1.23.3-alpine
    ports: 
      - "80:80" 
    volumes: 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf 
      - ../frontend/build:/usr/share/nginx/html/ 
      - ../docs/:/usr/share/nginx/html/api/docs/ 
      - static_dir:/etc/nginx/html/static/
      - media_dir:/etc/nginx/html/media/
    depends_on: 
      - frontend
      - backend
 
volumes:
  static_dir:
  media_dir:
  postgres_data:
