# Generated by Django 4.2 on 2023-04-14 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_subscription_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(inverse_match=True, regex='^[\\w$%^&#:;!]+\\Z')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(inverse_match=True, regex='^[\\w$%^&#:;!]+\\Z')], verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(inverse_match=True, regex='^[\\w$%^&#:;!]+\\Z')], verbose_name='Пользователь'),
        ),
    ]
