# Generated by Django 4.2 on 2023-04-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_alter_favorite_user_alter_shoppingcart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipe.IngredientInRecipe', to='recipe.ingredient', verbose_name='Ингредиенты'),
        ),
    ]
