# Generated by Django 4.2 on 2023-04-21 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0018_alter_shoppingcart_options_alter_favorite_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
    ]
